export const ACTIONS = {
    SET_DATA: "SET_DATA",
    SET_ERROR: "SET_ERROR",
    SET_LOADING: "SET_LOADING",
    SET_PARAMS: "SET_PARAMS",
    SET_PAGE: "SET_PAGE",
    RELOAD: "RELOAD",
    SET_ROW_PER_PAGE: "SET_ROW_PER_PAGE"
};